server:
  port: 8000

spring:
  datasource:
    username: root
    password: 123456789ww
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver



